### ISSUE TITLE
the trick of cube culling?

### ISSUE THREAD

**Issue by tianzjyh** [evanw/webgl-water#6]
In the cube vertex shader, the code below flips the inside and outside faces of the cube. So when enable GL_CULL_FACE, we can see the inside faces instead of the outside faces.
`      position = gl_Vertex.xyz;\
      position.y = ((1.0 - position.y) * (7.0 / 12.0) - 1.0) * poolHeight;\`

But why does the top face of the cube disappear when I look up from the bottom of the cube ? 
What's the trick here ? I just cannot find it.

![capture_0](https://cloud.githubusercontent.com/assets/24807656/21519487/7d45c10c-cd28-11e6-86cb-485dbef63032.png)
![capture_1](https://cloud.githubusercontent.com/assets/24807656/21519488/7d717bf8-cd28-11e6-96c0-5e9895012a4d.png)

**Comment by evanw** [comment]
I haven't looked at this code in a while, but I assume that was done by this line:

```js
this.cubeMesh.triangles.splice(4, 2);
```

**Comment by tianzjyh** [comment]
OK, I got it! Thanks!
I rewrote the code in OpenGL, but was not able to explain the difference of the results. 
Thanks for your answer.
